# Generated by Django 4.0.3 on 2022-10-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=100)),
                ('stuemail', models.CharField(max_length=50)),
                ('stupass', models.CharField(max_length=60)),
            ],
        ),
    ]
