# Generated by Django 4.0.3 on 2022-10-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studiv',
            field=models.CharField(default='not Available', max_length=30),
        ),
    ]
