# Generated by Django 4.0.3 on 2022-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=90)),
                ('stu_email', models.EmailField(max_length=20)),
                ('stu_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
